#项目名
application: seal-control
#版本号
version: v1
#端口号
server:
  port: 8888
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-security-demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
   # 下面为连接池的设置
    initialSize: 5
    minIdle: 10
    maxActive: 50
   # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
#指定mybatis映射文件地址
mybatis:
  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: com.iyin.cloud.cloudmodel
#打印日志ogging：日志文件放在tomcat目录下的logs里面
logging:
  file: logs/log.log
  level.com.iyin.cloud: DEBUG

thymeleaf:
    prefix: classpath:/public/templaters/
    cache: false

